### PR TITLE
BlueZ: Replace raw HCI sockets with BlueZ over DBus

### LINKED ISSUE #60: DeviceLost event is never fired.
**Describe the bug**
I did small modification by adding  device lost event processing
            CentralEvent::DeviceLost(bd_addr) => {
                println!("DeviceLost: {:?}", bd_addr);

and that looks like program prints 'Discovered event' only after turning on BLE device.
Is 'DeviceLost' event not fired? I see description in comments:
> The first time the getter/ is called, it will return Some(Receiver<CentralEvent>). After that, it  will only return None

If that example does not works properly so probably it's worth deleting?

**Expected behavior**
I expected to see correct Discovered/Lost events processed for turned on/off device

**Actual behavior**
Program prints 'Discovered event' only after turning on BLE device.
When I try turn on/off device several times on Linux, it doesn't work, only one event if fired.

**Additional context**
Linux Mint 20, x64

### PR DESCRIPTION
**Pull request by NZSmartie**
This is a complete rewrite of the "bluez" platform specific code.

A lot has happened and I did my best to commend code to explain how/why a well as keep commits subjective so that changes can be understood in context.

Things I want to do before merging:
- [ ] ~~Verify I didn't break the existing API~~ (Maintaining a backwards compatible API is a lot harder than I thought and ends up with a lot of messy dead code)
- [ ] Ensure both passive and active discovery work as intended
- [x] Ensure the code isn't too terrible looking
- [ ] Test this library against multiple versions of BlueZ to see what fails where

Closes #60, #69

### CODE REVIEW

**Comment by NZSmartie** [comment]
I had a look through other open issues and found two related issues that will be resolved with this PR

**Comment by NZSmartie** [comment]
@qdot, can you add `libdbus-1-dev` to Linux's installed packages on the CI pipeline?

**Comment by NZSmartie** [comment]
I've done what I can to test this PR, and I'm now relying on others to help test it. Since it works for me™, I'm happy to submit future PRs to fix bugs or other issues that I've yet to face

**Comment by NZSmartie** [comment]
just rebased on to master

**Comment by lnicola** [comment]
Also closes #52.

**Comment by qdot** [comment]
Awesome, thanks for the updates. I am definitely trying to get to reviewing this, hopefully in the next day or two.

**Comment by qdot** [comment]
(Note: This is permission to yell at me in these here comments if I don't get to it soon :3 )

File: src/bluez/adapter/mod.rs [hunk 1]
```diff
@@ -11,517 +11,478 @@
...
 
-    pub fn is_up(&self) -> bool {
-        self.states.contains(&AdapterState::Up)
+    fn peripheral(&self, address: BDAddr) -> Option<Peripheral> {
+        self.manager.peripheral(address)
     }
 
-    pub fn connect(&self) -> Result<ConnectedAdapter> {
-        ConnectedAdapter::new(self)
+    fn active(&self, _enabled: bool) {
```
Comment (qdot) [inline src/bluez/adapter/mod.rs:485]: Here and elsewhere, can we get some comments on the methods that need to be filled in? Makes it easier to file help wanted bugs or at least say issues are claimed later, if we know what needs to be filled in.

File: src/bluez/adapter/peripheral.rs [hunk 2]
```diff
@@ -11,410 +11,404 @@
...
+    connection: Arc<SyncConnection>,
+    path: String,
     address: BDAddr,
     properties: Arc<Mutex<PeripheralProperties>>,
     characteristics: Arc<Mutex<BTreeSet<Characteristic>>>,
-    stream: Arc<RwLock<Option<ACLStream>>>,
-    connection_tx: Arc<Mutex<Sender<u16>>>,
-    connection_rx: Arc<Mutex<Receiver<u16>>>,
-    message_queue: Arc<Mutex<VecDeque<ACLData>>>,
+    attributes_map: Arc<Mutex<HashMap<u16, (String, Handle, Characteristic)>>>,
```
Comment (qdot) [inline src/bluez/adapter/peripheral.rs:58]: If you wanted to lose the Mutex here, you could switch to DashMap. I use it heavily up in Buttplug, works great. That said, with everything else so lock heavy here, that's really just the lightest of nits and could be a followup.

File: src/bluez/adapter/peripheral.rs [hunk 3]
```diff
@@ -11,410 +11,404 @@
...
+                self.address, manufacturer_data
+            );
+            let mut result = Vec::<u8>::new();
+            // dbus-rs doesn't really have a dictionary API... so need to iterate two at a time and make a key-value pair.
+            if let Some(mut iter) = manufacturer_data.0.as_iter() {
+                loop {
+                    if let (Some(id), Some(data)) = (iter.next(), iter.next()) {
+                        // This API is terrible.. why can't I just get an array out, why is it all wrapped in a Variant?
+                        let data: Vec<u8> = data
+                            .as_iter() // 🎶 The Variant is connected to the
```
Comment (qdot) [inline src/bluez/adapter/peripheral.rs:318]: I like this, please go through the rest of your patch and make your comments rhyme.

File: src/bluez/adapter/peripheral.rs [hunk 4]
```diff
@@ -512,154 +472,126 @@ impl ApiPeripheral for Peripheral {
...
-            lock.insert(c.clone());
-        });
+        debug!("All services are now resolved!");
 
-        Ok(results)
+        Ok(self
+            .characteristics
+            .lock()
+            .unwrap()
+            .clone()
```
Comment (qdot) [inline src/bluez/adapter/peripheral.rs:494]: Very nit: You *might* be able to use cloned() after your map (and use refs up to that point), save the copy then discard? But it honestly doesn't matter much in this context, and I can't remember off the top of my head where cloned() comes in.

**Review by qdot — CHANGES_REQUESTED** [review]
This is all looking really good! I've just got a few comments I'd like addressed, then it can land.

File: src/bluez/adapter/peripheral.rs [hunk 5]
```diff
@@ -11,410 +11,404 @@
...
+                        // This API is terrible.. why can't I just get an array out, why is it all wrapped in a Variant?
+                        let data: Vec<u8> = data
+                            .as_iter() // 🎶 The Variant is connected to the
+                            .unwrap() // Array type!
+                            .next() // The Array type is connected to the
+                            .unwrap() // Array of integers!
+                            .as_iter() // Lets convert the
+                            .unwrap() // integers to a
+                            .map(|b| b.as_u64().unwrap() as u8) // array of bytes...
+                            .collect(); // I got too lazy to make it rhyme... 🎶
```
Comment (qwandor) [inline src/bluez/adapter/peripheral.rs:325]: You can do this more nicely with `dbus::arg::prop_cast`, or if you pass `--prop-newtype` to `dbus-codegen-rust` it will give you a type-safe wrapper for the `HashMap`, and you can do `OrgBluezDevice1Properties::manufacturer_data` to get a `HashMap<u16, Variant<Box<dyn RefArg>>>`, and then you can just map the values with `dbus::arg::cast::<Vec<u8>>(&v.0)`.

**Comment by qdot** [comment]
@qwandor Thanks for the comment! 

If you or anyone else has additional guidance on the Bluez side, please feel free to add it here. I was mostly reviewing for structure, I'm far more familiar with the CoreBluetooth and UWP sides of the library, so I can't really comment much on the Bluez.

File: src/bluez/adapter/mod.rs [hunk 6]
```diff
@@ -11,517 +11,478 @@
...
-                set.insert(f.clone());
+        // Spawn a new thread to process incoming DBus messages.
+        // This thread gets cleaned up in the 'impl Drop for Adapter'
+        *self.thread_handle.lock().unwrap() = Some(thread::spawn(move || {
+            while !should_stop.load(Ordering::Relaxed) {
+                // listener is protected by a mutex. as calling `process()` when a proxy is awaiting a reply will cause the reply to be dropped...
+                let lock = listener.lock();
+                while lock.process(Duration::from_secs(0)).unwrap() {}
+                drop(lock);
+                thread::sleep(Duration::from_millis(100));
```
[the remark this answers is not in the document]
Comment (NZSmartie) [reply src/bluez/adapter/mod.rs:160]: no source for this. I was going for a way to quickly process any messages there may be, and then sleeping on the thread for 100ms, so that other threads have a chance to use the listener to send/receive

File: src/bluez/adapter/peripheral.rs (hunk 5 above)
Comment (NZSmartie) [reply src/bluez/adapter/peripheral.rs:325]: From memory, I gave this a try from the very start. but I think because i'm passing in a subset of the type that `dbus::arg::cast/prop_cast` are expecting, i get compile errors. I'll have another go and see if I've missed something.

Comment (qwandor) [reply src/bluez/adapter/peripheral.rs:325]: Ah, you may also need to make sure you have at least version 0.9.1 of the `dbus` crate, to include the fix from https://github.com/diwic/dbus-rs/pull/306.

File: src/bluez/adapter/mod.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (NZSmartie) [reply src/bluez/adapter/mod.rs:160]: Looking back at my code and later learning about `parking_lot` I was dealing with mutex _fairness_, where, the `while` loop was constantly locking the mutex, not giving any other threads a chance to get a lock, and thus, anything that needed `listener` would block. 

I'll see if `parking_lot::ReentrantMutex` promotes fairness

File: src/bluez/adapter/peripheral.rs (hunk 5 above)
Comment (qwandor) [reply src/bluez/adapter/peripheral.rs:325]: I've sent you https://github.com/NZSmartie/btleplug/pull/1 to fix this.

Comment (NZSmartie) [reply src/bluez/adapter/peripheral.rs]: Thanks @qwandor! Though i'm a bit sad to see my silly rhyming comment go away 😢

Comment (qdot) [reply src/bluez/adapter/peripheral.rs]: We need to keep some standards in this code, so I'm at least going to need some methods in iambic pentameter going forward.

**Review by qdot — APPROVED** [review]

**Comment by qdot** [comment]
Ok, well, I'm cool with the changes and will land this, just gotta figure out why changing the base branch to dev borkt things because master and dev are on the same HEAD. I'd also like to keep my fast-forward only rule so I may rebase out the merge that comes in here. So, in short: Your code will be into the `dev` branch probably this evening, but may look slightly different than your commit lineup here, so you may need to reset if you had changes on your `dev`.

**Comment by qdot** [comment]
Ok, I just brought this in with the merges for now, turns out the prehistory of rumble is just lousy with them anyways.
